"""add program_id to donations

Revision ID: 17b2c15d922e
Revises: 367d7bc53533
Create Date: 2025-09-14 10:24:09.752820
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17b2c15d922e'
down_revision = '367d7bc53533'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('program_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            'fk_donations_program_id',   # 👈 give it a name
            'programs',
            ['program_id'],
            ['id']
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_donations_program_id',   # 👈 use same name here
            type_='foreignkey'
        )
        batch_op.drop_column('program_id')
    # ### end Alembic commands ###
